# Generated by Django 5.2 on 2025-05-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
