# Generated by Django 5.2 on 2025-05-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employees_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='bday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='doh',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='head',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='spv',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
