# Generated by Django 5.2 on 2025-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employees_bday_employees_doh_employees_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='bdayP',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='dohP',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
