# Generated by Django 5.2 on 2025-05-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employees_bdayp_employees_dohp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='bdayP',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='dohP',
        ),
    ]
